// PDF export. Two-page letter layout via vendored jsPDF: page 1 has the
// title (from current fly-out context), map snapshot via vendored
// leaflet-image, and a Summary table with ACREAGE prominent; page 2 holds
// Hazards / Terrain / Soil / Notes. The map snapshot temporarily switches to
// CARTO Voyager (which sends ACAO: *) so the canvas isn't tainted, then
// restores the original basemap. Snapshot failures fall back silently to a
// text-only PDF with a small "Map snapshot unavailable" note.

import { map, withCorsCompatibleBasemap } from './map.js';
import { showToast } from './overlays.js';
import { getFlyoutContext } from './flyout.js';
import { savedPlaces } from './saved-places.js';
import { PARCEL_COUNTIES } from './config.js';

const btn = document.getElementById('export-pdf');
if (btn) btn.addEventListener('click', exportPdf);

const SNAPSHOT_TIMEOUT_MS = 8000;
const IMG_W = 480, IMG_H = 360;
const PAGE_W = 612, PAGE_H = 792;   // letter @ 72dpi (pt)
const MARGIN = 56;
const FOOTER_Y = PAGE_H - 32;

function readout(id) {
  const el = document.getElementById(id);
  return el ? el.textContent.trim() : '—';
}

function pickField(props, candidates) {
  if (!props) return null;
  for (const k of candidates || []) {
    if (props[k] !== undefined && props[k] !== null && props[k] !== '') return props[k];
  }
  return null;
}

// Mirror the fly-out's header hierarchy so the PDF title matches what the
// user was looking at when they hit Export.
function deriveTitle(ctx) {
  const { lat, lng, parcelId, parcelMeta, geocode } = ctx;
  if (lat != null && lng != null) {
    const saved = savedPlaces.findByCoords(lat, lng);
    if (saved && saved.label) return { primary: saved.label, savedNotes: saved.notes };
  }
  if (parcelId) {
    let owner = null;
    if (parcelMeta?.county) {
      owner = pickField(parcelMeta, PARCEL_COUNTIES[parcelMeta.county]?.fieldMap?.owner);
    }
    return { primary: owner ? `Parcel ${parcelId} — ${owner}` : `Parcel ${parcelId}` };
  }
  if (geocode?.address) {
    const approx = geocode.confidence !== 'high';
    return { primary: approx ? `Near ~ ${geocode.address}` : `Near ${geocode.address}` };
  }
  if (lat != null && lng != null) return { primary: `${lat.toFixed(5)}, ${lng.toFixed(5)}` };
  return { primary: 'Land Analysis' };
}

function buildContext() {
  const c = map.getCenter();
  const z = map.getZoom();
  const flyoutCtx = getFlyoutContext();
  const lat = flyoutCtx.lat ?? c.lat;
  const lng = flyoutCtx.lng ?? c.lng;
  const title = deriveTitle({ ...flyoutCtx, lat, lng });

  const meta = flyoutCtx.parcelMeta || null;
  const countyKey = meta?.county;
  const countyCfg = countyKey ? PARCEL_COUNTIES[countyKey] : null;
  const parcelOwner = meta && countyCfg ? pickField(meta, countyCfg.fieldMap?.owner) : null;
  const parcelValue = meta && countyCfg ? pickField(meta, countyCfg.fieldMap?.value) : null;
  return {
    title: title.primary,
    notes: title.savedNotes ?? null,
    generated: new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC',
    location: { lat, lng, zoom: z },
    parcel: {
      id: flyoutCtx.parcelId || readout('p-id'),
      owner: parcelOwner ?? readout('p-owner'),
      acreage: readout('p-acres'),
      value: parcelValue != null ? String(parcelValue) : readout('p-value'),
      county: countyCfg?.label || readout('p-county')
    },
    hazards: {
      flood: readout('r-flood'),
      floodDesc: readout('r-flood-desc') || ''
    },
    terrain: {
      elevation: readout('r-elev')
    },
    soil: {
      mapUnit: readout('s-name'),
      drainage: readout('s-drain'),
      hydric: readout('s-hydric'),
      farmland: readout('s-farm'),
      parent: readout('s-parent')
    }
  };
}

async function captureMapSnapshot() {
  if (typeof window.leafletImage !== 'function') return null;
  return withCorsCompatibleBasemap(() => new Promise((resolve) => {
    const timer = setTimeout(() => resolve(null), SNAPSHOT_TIMEOUT_MS);
    try {
      window.leafletImage(map, (err, canvas) => {
        clearTimeout(timer);
        if (err || !canvas) return resolve(null);
        try { resolve(canvas.toDataURL('image/png')); }
        catch { resolve(null); }
      });
    } catch {
      clearTimeout(timer);
      resolve(null);
    }
  }));
}

// Wrap text to maxWidth, but cap total lines so a long section can't push
// content off the page. Truncated with an ellipsis hint.
function wrap(doc, text, maxWidth, maxLines = 4) {
  if (text == null || text === '') return ['—'];
  const lines = doc.splitTextToSize(String(text), maxWidth);
  if (lines.length <= maxLines) return lines;
  return [...lines.slice(0, maxLines - 1), '… see app for full details'];
}

function drawFooter(doc, pageLabel) {
  doc.setFontSize(8);
  doc.setTextColor(140);
  doc.text(
    `Generated by PARCEL — verify with surveyor / title company before any purchase decision.`,
    MARGIN, FOOTER_Y
  );
  doc.text(pageLabel, PAGE_W - MARGIN - 20, FOOTER_Y);
  doc.setTextColor(0);
}

function drawSection(doc, title, rows, startY, options = {}) {
  const labelW = options.labelW ?? 150;
  const valueW = PAGE_W - MARGIN * 2 - labelW;
  let y = startY;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, MARGIN, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  for (const [label, value] of rows) {
    const valueLines = wrap(doc, value, valueW, 4);
    doc.setTextColor(110);
    doc.text(`${label}`, MARGIN, y);
    doc.setTextColor(0);
    for (let i = 0; i < valueLines.length; i++) {
      doc.text(valueLines[i], MARGIN + labelW, y + i * 13);
    }
    y += Math.max(14, valueLines.length * 13 + 2);
  }
  return y + 6;
}

export async function exportPdf() {
  const ctor = window.jspdf && window.jspdf.jsPDF;
  if (!ctor) {
    showToast('PDF library not loaded');
    return null;
  }
  const ctx = buildContext();
  const doc = new ctor({ unit: 'pt', format: 'letter' });

  let snapshot = null;
  try { snapshot = await captureMapSnapshot(); }
  catch { snapshot = null; }

  // ============ PAGE 1: cover / summary ============
  let y = MARGIN;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  const titleLines = wrap(doc, ctx.title, PAGE_W - MARGIN * 2, 2);
  for (const line of titleLines) {
    doc.text(line, MARGIN, y);
    y += 24;
  }
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(`Generated ${ctx.generated}`, MARGIN, y);
  doc.setTextColor(0);
  y += 18;

  if (snapshot) {
    try {
      doc.addImage(snapshot, 'PNG', MARGIN, y, IMG_W, IMG_H);
      y += IMG_H + 16;
    } catch {
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text('Map snapshot unavailable.', MARGIN, y);
      doc.setTextColor(0);
      y += 16;
    }
  } else {
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text('Map snapshot unavailable.', MARGIN, y);
    doc.setTextColor(0);
    y += 16;
  }

  // Summary table — acreage on this page, prominently styled
  y = drawSection(doc, 'Summary', [
    ['Parcel ID', ctx.parcel.id],
    ['Owner', ctx.parcel.owner],
    ['Acreage', ctx.parcel.acreage],
    ['Assessed Value', ctx.parcel.value],
    ['County / State', ctx.parcel.county]
  ], y);

  drawFooter(doc, 'Page 1 of 2');

  // ============ PAGE 2: detailed findings ============
  doc.addPage();
  y = MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Detailed Findings', MARGIN, y);
  y += 24;

  y = drawSection(doc, 'Hazards', [
    ['Flood Zone', ctx.hazards.flood],
    ['Meaning', ctx.hazards.floodDesc || 'No flood zone description available.']
  ], y);

  y = drawSection(doc, 'Terrain', [
    ['Elevation', ctx.terrain.elevation]
  ], y);

  y = drawSection(doc, 'Soil', [
    ['Map Unit', ctx.soil.mapUnit],
    ['Drainage Class', ctx.soil.drainage],
    ['Hydric Rating', ctx.soil.hydric],
    ['Farmland Classification', ctx.soil.farmland],
    ['Parent Material', ctx.soil.parent]
  ], y);

  if (ctx.notes) {
    y = drawSection(doc, 'Notes', [['User Notes', ctx.notes]], y);
  }

  // Precise coords pinned to the bottom of page 2 (above the footer)
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(110);
  const coordY = FOOTER_Y - 16;
  doc.text(
    `Location: ${ctx.location.lat.toFixed(6)}, ${ctx.location.lng.toFixed(6)}  ·  zoom ${ctx.location.zoom}`,
    MARGIN, coordY
  );
  doc.setTextColor(0);

  drawFooter(doc, 'Page 2 of 2');

  const filename = `parcel-${ctx.location.lat.toFixed(4)}_${ctx.location.lng.toFixed(4)}.pdf`;
  doc.save(filename);
  return { doc, filename };
}

export const exportApi = { exportPdf };
